docker pull cloudsuite/web-serving:web_server
docker pull cloudsuite/web-serving:memcached_server
docker pull cloudsuite/web-serving:faban_client
docker pull cloudsuite/web-serving:db_server
docker pull cloudsuite/web-search:server
docker pull cloudsuite/web-search:client
docker pull cloudsuite/twitter-dataset-graph:4.0
docker pull cloudsuite/siege:4.0.3rc3
docker pull cloudsuite/mysql:mariadb-10.3
docker pull cloudsuite/movielens-dataset:4.0
docker pull cloudsuite/media-streaming:dataset
docker pull cloudsuite/in-memory-analytics:4.0
docker pull cloudsuite/hadoop:2.10.1
docker pull cloudsuite/graph-analytics:4.0
docker pull cloudsuite/fb-oss-performance:4.0
docker pull cloudsuite/django-workload:uwsgi
docker pull cloudsuite/django-workload:siege
docker pull cloudsuite/django-workload:memcached
docker pull cloudsuite/django-workload:graphite
docker pull cloudsuite/django-workload:cassandra
docker pull cloudsuite/data-caching:server
docker pull cloudsuite/data-caching:client
docker pull cloudsuite/data-analytics:4.0
docker pull cloudsuite/media-streaming.dataset
